package com.example.servletjspdemo.service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.example.servletjspdemo.domain.Cigarette;

public class CigaretteHandler implements CigBase {
	private Connection connection;

	private String url = "jdbc:hsqldb:hsql://localhost/workdb";

	private String createTableCig = "CREATE TABLE Cigarette(id INTEGER GENERATED BY DEFAULT AS IDENTITY, Name VARCHAR(40), Price DECIMAL(8,2), Count INTEGER, PRIMARY KEY(id));";

	private String getAllCigStmt = "SELECT id, Name, Price, Count FROM Cigarette;";
	
	private PreparedStatement addCigStmt;
	private PreparedStatement deleteAllCigStmt;
	private PreparedStatement deleteCigStmt;
	private PreparedStatement replaceCigStmt;

	private Statement statement;
	
	public CigaretteHandler() {
		try {
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();

			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("Cigarette".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}

			if (!tableExists)
				statement.executeUpdate(createTableCig);

			addCigStmt = connection.prepareStatement("INSERT INTO Cigarette(Name, Price, Count) VALUES (?, ?, ?);");
			deleteAllCigStmt = connection.prepareStatement("DELETE FROM Cigarette;");
			deleteCigStmt = connection.prepareStatement("DELETE FROM Cigarette WHERE id = ?;");
			replaceCigStmt = connection.prepareStatement("UPDATE Cigarette SET Name = ?, Price = ?, Count = ? WHERE id = ?;");
			System.out.println("Connected!");
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	public List<Cigarette> getAllCigarettes() {
		List<Cigarette> cigs = new ArrayList<Cigarette>();

		try {
			ResultSet rs = statement.executeQuery(getAllCigStmt);

			while (rs.next()) {
				Cigarette p = new Cigarette();
				p.setId(rs.getInt("id"));
				p.setName(rs.getString("Name"));
				p.setPrice(rs.getDouble("Price"));
				p.setCount(rs.getInt("Count"));
				cigs.add(p);
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return cigs;
	}
	public int addCigarette(Cigarette cig) {
		int count = 0;
		try {
			addCigStmt.setString(1, cig.getName());
			addCigStmt.setDouble(2, cig.getPrice());
			addCigStmt.setInt(3, cig.getCount());

			count = addCigStmt.executeUpdate();

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return count;
	}
	public void removeCigarette(Cigarette cig) {
		try {
			deleteCigStmt.setInt(1, cig.getId());

			deleteCigStmt.executeUpdate();

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	public void removeAllCigarettes() {
		try {
			deleteAllCigStmt.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	public void replaceCigarette(Cigarette oldcig, Cigarette newcig) {
		try {
			replaceCigStmt.setString(1, newcig.getName());
			replaceCigStmt.setDouble(2, newcig.getPrice());
			replaceCigStmt.setInt(3, newcig.getCount());
			replaceCigStmt.setInt(4, oldcig.getId());
			
			addCigStmt.executeUpdate();

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

}
